chefs = [
    {
        "id": 1,
        "emoji": "👩🏾‍🍳",
        "name": "Anika Osei",
        "location": "Brooklyn, NY",
        "experience": 3,
        "tags": ["West African", "Caribbean", "Pantry Chef"],
        "rating": 4.9,
        "reviewCount": 48,
        "price": 85,
        "badge": "Premium",
        "subtitle": "West African & Caribbean · Brooklyn, NY · Cuisine Chef & Pantry Chef",
        "bookingCount": 124,
        "bio": "I grew up cooking West African and Caribbean food with my grandmother. I specialise in Jollof, Egusi soup, Ackee & Saltfish, Oxtail, and can work with whatever ingredients you already have at home. Let me bring the flavours of home to your table.",
        "dishes": ["Jollof Rice", "Egusi Soup", "Ackee & Saltfish", "Oxtail Stew", "Suya Skewers", "Puff Puff"],
        "availability": [
            {"day": "Mon", "hours": None},
            {"day": "Tue", "hours": "4–9pm"},
            {"day": "Wed", "hours": "4–9pm"},
            {"day": "Thu", "hours": None},
            {"day": "Fri", "hours": "3–10pm"},
            {"day": "Sat", "hours": "All day"},
            {"day": "Sun", "hours": "12–7pm"},
        ],
        "reviews": [
            {"id": 1, "user": "Marcus T.", "rating": 5, "comment": "Anika made the best Jollof I've ever had outside of Lagos. She came in, checked my pantry, and worked with what I had. Absolutely amazing experience for my family dinner."},
            {"id": 2, "user": "Sandra K.", "rating": 5, "comment": "We requested a full Caribbean spread for 8 people — oxtail, rice & peas, plantains — everything was perfect. Anika was professional, clean, and so warm with our guests."},
            {"id": 3, "user": "Jamal F.",  "rating": 4, "comment": "Great pantry chef experience. Told her what I had and she made something completely different than I expected — in the best way. Will book again."},
        ],
    },
    {
        "id": 2,
        "emoji": "👨🏻‍🍳",
        "name": "Marco Ferretti",
        "location": "Manhattan, NY",
        "experience": 7,
        "tags": ["Italian", "Mediterranean"],
        "rating": 4.8,
        "reviewCount": 91,
        "price": 110,
        "badge": None,
        "subtitle": "Italian & Mediterranean · Manhattan, NY · Cuisine Chef",
        "bookingCount": 310,
        "bio": "Trained in Bologna and New York, I bring authentic Italian technique to your home kitchen. From handmade pasta to wood-fired-style roasts, every meal is built around fresh, seasonal ingredients.",
        "dishes": ["Tagliatelle al Ragù", "Osso Buco", "Risotto ai Funghi", "Tiramisu", "Bruschetta", "Saltimbocca"],
        "availability": [
            {"day": "Mon", "hours": "5–10pm"},
            {"day": "Tue", "hours": "5–10pm"},
            {"day": "Wed", "hours": None},
            {"day": "Thu", "hours": "5–10pm"},
            {"day": "Fri", "hours": "4–11pm"},
            {"day": "Sat", "hours": "All day"},
            {"day": "Sun", "hours": None},
        ],
        "reviews": [
            {"id": 1, "user": "Claire B.", "rating": 5, "comment": "Marco cooked a five-course Italian dinner for our anniversary. Every single dish was restaurant quality. Worth every penny."},
            {"id": 2, "user": "Tony R.",   "rating": 5, "comment": "The handmade pasta alone was worth it. Incredible experience from start to finish."},
        ],
    },
    {
        "id": 3,
        "emoji": "👩🏽‍🍳",
        "name": "Priya Nair",
        "location": "Queens, NY",
        "experience": 2,
        "tags": ["Indian", "South Asian", "Vegan"],
        "rating": 4.7,
        "reviewCount": 22,
        "price": 70,
        "badge": "New",
        "subtitle": "Indian & South Asian · Queens, NY · Cuisine Chef",
        "bookingCount": 34,
        "bio": "I specialise in South Indian and North Indian home cooking — from fragrant biryanis to fresh dosas and plant-based curries. Food should feel like a hug, and that's what I aim to deliver.",
        "dishes": ["Chicken Biryani", "Masala Dosa", "Dal Makhani", "Paneer Butter Masala", "Rasam", "Gulab Jamun"],
        "availability": [
            {"day": "Mon", "hours": None},
            {"day": "Tue", "hours": None},
            {"day": "Wed", "hours": "5–9pm"},
            {"day": "Thu", "hours": "5–9pm"},
            {"day": "Fri", "hours": "4–9pm"},
            {"day": "Sat", "hours": "All day"},
            {"day": "Sun", "hours": "12–6pm"},
        ],
        "reviews": [
            {"id": 1, "user": "Ananya S.", "rating": 5, "comment": "Priya made the most comforting dal and biryani I've had since visiting India. Her prices are very fair for the quality."},
            {"id": 2, "user": "Ben W.",    "rating": 4, "comment": "Great vegan spread. She was flexible with my dietary needs and everything tasted incredible."},
        ],
    },
    {
        "id": 4,
        "emoji": "👨🏿‍🍳",
        "name": "Kwame Asante",
        "location": "Bronx, NY",
        "experience": 5,
        "tags": ["Ghanaian", "Jollof Specialist"],
        "rating": 5.0,
        "reviewCount": 17,
        "price": 90,
        "badge": None,
        "subtitle": "Ghanaian Cuisine · Bronx, NY · Cuisine Chef",
        "bookingCount": 55,
        "bio": "Born in Accra, raised in the Bronx. I cook authentic Ghanaian food — the kind you can't find in most restaurants. My Jollof is a point of pride, and my kontomire stew will remind you of home.",
        "dishes": ["Ghanaian Jollof", "Kontomire Stew", "Fufu & Light Soup", "Kelewele", "Waakye", "Banku & Tilapia"],
        "availability": [
            {"day": "Mon", "hours": "5–9pm"},
            {"day": "Tue", "hours": None},
            {"day": "Wed", "hours": "5–9pm"},
            {"day": "Thu", "hours": None},
            {"day": "Fri", "hours": "4–10pm"},
            {"day": "Sat", "hours": "All day"},
            {"day": "Sun", "hours": "1–7pm"},
        ],
        "reviews": [
            {"id": 1, "user": "Ama D.",   "rating": 5, "comment": "Finally found someone who cooks Ghanaian food the right way in New York. Kwame is the real deal."},
            {"id": 2, "user": "Derek O.", "rating": 5, "comment": "Best Jollof I've ever had — and I've been to Ghana twice. Absolutely phenomenal."},
        ],
    },
    {
        "id": 5,
        "emoji": "👩🏻‍🍳",
        "name": "Yuki Tanaka",
        "location": "Manhattan, NY",
        "experience": 10,
        "tags": ["Japanese", "Omakase", "Sushi"],
        "rating": 4.9,
        "reviewCount": 63,
        "price": 150,
        "badge": None,
        "subtitle": "Japanese · Manhattan, NY · Cuisine Chef",
        "bookingCount": 201,
        "bio": "A decade of training in Tokyo and New York's finest Japanese kitchens. I offer omakase-style private dining experiences — a curated journey through seasonal Japanese cuisine right in your home.",
        "dishes": ["Omakase Sushi", "Miso Black Cod", "Wagyu Shabu-shabu", "Chawanmushi", "Matcha Panna Cotta", "Tonkotsu Ramen"],
        "availability": [
            {"day": "Mon", "hours": None},
            {"day": "Tue", "hours": "6–11pm"},
            {"day": "Wed", "hours": "6–11pm"},
            {"day": "Thu", "hours": "6–11pm"},
            {"day": "Fri", "hours": "5–11pm"},
            {"day": "Sat", "hours": "All day"},
            {"day": "Sun", "hours": None},
        ],
        "reviews": [
            {"id": 1, "user": "James L.",  "rating": 5, "comment": "Yuki delivered a 9-course omakase experience for my wife's birthday. It was the best meal we've ever had at home. Transcendent."},
            {"id": 2, "user": "Rachel T.", "rating": 5, "comment": "The attention to detail is unlike anything I've seen. Every piece of sushi was perfect."},
        ],
    },
    {
        "id": 6,
        "emoji": "👨🏽‍🍳",
        "name": "Diego Vargas",
        "location": "Queens, NY",
        "experience": 6,
        "tags": ["Mexican", "Colombian", "Pantry Chef"],
        "rating": 4.8,
        "reviewCount": 39,
        "price": 95,
        "badge": "Premium",
        "subtitle": "Mexican & Colombian · Queens, NY · Cuisine Chef & Pantry Chef",
        "bookingCount": 142,
        "bio": "I cook the food I grew up with — rich Mexican moles, fresh Colombian arepas, and everything in between. I love working as a pantry chef too, finding creative ways to use what's already in your kitchen.",
        "dishes": ["Mole Negro", "Arepas con Hogao", "Tacos al Pastor", "Bandeja Paisa", "Chiles Rellenos", "Tres Leches"],
        "availability": [
            {"day": "Mon", "hours": "4–9pm"},
            {"day": "Tue", "hours": "4–9pm"},
            {"day": "Wed", "hours": None},
            {"day": "Thu", "hours": "4–9pm"},
            {"day": "Fri", "hours": "3–10pm"},
            {"day": "Sat", "hours": "All day"},
            {"day": "Sun", "hours": "12–7pm"},
        ],
        "reviews": [
            {"id": 1, "user": "Maria G.", "rating": 5, "comment": "Diego's mole negro was the real thing — complex, rich, and took me right back to Oaxaca. Exceptional chef."},
            {"id": 2, "user": "Luis P.",  "rating": 5, "comment": "The bandeja paisa was perfect. He cooked for 10 people and every dish came out flawless."},
        ],
    },
]

users = [
    {
        "id": 1,
        "name": "David M.",
        "initials": "DM",
        "email": "david@example.com",
        "password": "password123",
    },
    {
        "id": 2,
        "name": "Sandra K.",
        "initials": "SK",
        "email": "sandra@example.com",
        "password": "chefconnect",
    },
]

bookings = [
    {
        "id": 1,
        "emoji": "👩🏾‍🍳",
        "chef": "Anika Osei",
        "chef_id": 1,
        "user_id": 1,
        "cuisine": "West African",
        "date": "May 10, 2026",
        "amount": "$198.50",
        "status": "confirmed",
    },
    {
        "id": 2,
        "emoji": "👨🏻‍🍳",
        "chef": "Marco Ferretti",
        "chef_id": 2,
        "user_id": 1,
        "cuisine": "Italian",
        "date": "Apr 28, 2026",
        "amount": "$246.00",
        "status": "completed",
    },
    {
        "id": 3,
        "emoji": "👩🏽‍🍳",
        "chef": "Priya Nair",
        "chef_id": 3,
        "user_id": 1,
        "cuisine": "Indian",
        "date": "Apr 15, 2026",
        "amount": "$156.00",
        "status": "completed",
    },
    {
        "id": 4,
        "emoji": "👨🏿‍🍳",
        "chef": "Kwame Asante",
        "chef_id": 4,
        "user_id": 1,
        "cuisine": "Ghanaian",
        "date": "Mar 30, 2026",
        "amount": "$178.50",
        "status": "pending",
    },
]
